// <auto-generated />
using System;
using DemoApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119055930_qlkh")]
    partial class qlkh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DemoApp.Models.BaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DuongDanNoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiNoiDung")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Video");

                    b.Property<string>("TenBaiHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("BaiHoc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DuongDanNoiDung = "bai-1-gioi-thieu-html.mp4",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Giới thiệu về HTML",
                            ThuTuHienThi = 1
                        },
                        new
                        {
                            Id = 2,
                            DuongDanNoiDung = "bai-2-the-html-co-ban.mp4",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Thẻ HTML cơ bản",
                            ThuTuHienThi = 2
                        },
                        new
                        {
                            Id = 3,
                            DuongDanNoiDung = "bai-3-form-input.mp4",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Form và Input trong HTML",
                            ThuTuHienThi = 3
                        },
                        new
                        {
                            Id = 4,
                            DuongDanNoiDung = "bai-4-css-selectors.mp4",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "CSS Selectors cơ bản",
                            ThuTuHienThi = 4
                        },
                        new
                        {
                            Id = 5,
                            DuongDanNoiDung = "bai-5-bai-tap-thuc-hanh.pdf",
                            KhoaHocId = 1,
                            LoaiNoiDung = "PDF",
                            TenBaiHoc = "Bài tập thực hành HTML CSS",
                            ThuTuHienThi = 5
                        },
                        new
                        {
                            Id = 6,
                            DuongDanNoiDung = "bai-1-android-studio.mp4",
                            KhoaHocId = 2,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Giới thiệu Android Studio",
                            ThuTuHienThi = 1
                        },
                        new
                        {
                            Id = 7,
                            DuongDanNoiDung = "bai-2-layout-view.mp4",
                            KhoaHocId = 2,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Layout và View trong Android",
                            ThuTuHienThi = 2
                        },
                        new
                        {
                            Id = 8,
                            DuongDanNoiDung = "bai-3-xu-ly-su-kien.mp4",
                            KhoaHocId = 2,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Xử lý sự kiện click",
                            ThuTuHienThi = 3
                        },
                        new
                        {
                            Id = 9,
                            DuongDanNoiDung = "bai-4-intent-activity.mp4",
                            KhoaHocId = 2,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Intent và Activity",
                            ThuTuHienThi = 4
                        },
                        new
                        {
                            Id = 10,
                            DuongDanNoiDung = "bai-5-du-an-calculator.pdf",
                            KhoaHocId = 2,
                            LoaiNoiDung = "PDF",
                            TenBaiHoc = "Dự án ứng dụng Calculator",
                            ThuTuHienThi = 5
                        });
                });

            modelBuilder.Entity("DemoApp.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("DemoApp.Models.DangKyKhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DangHoc");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "KhoaHocId")
                        .IsUnique();

                    b.ToTable("DangKyKhoaHoc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KhoaHocId = 1,
                            NgayDangKy = new DateTime(2025, 11, 19, 12, 59, 30, 339, DateTimeKind.Local).AddTicks(8404),
                            TrangThai = "DangHoc",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            KhoaHocId = 2,
                            NgayDangKy = new DateTime(2025, 11, 19, 12, 59, 30, 339, DateTimeKind.Local).AddTicks(8406),
                            TrangThai = "DangHoc",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DemoApp.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("DanhMuc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "Học phát triển website",
                            TenDanhMuc = "Lập Trình Web",
                            ThuTuHienThi = 1,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "Phát triển ứng dụng di động",
                            TenDanhMuc = "Lập Trình Mobile",
                            ThuTuHienThi = 2,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            MoTa = "SQL Server, MySQL",
                            TenDanhMuc = "Cơ Sở Dữ Liệu",
                            ThuTuHienThi = 3,
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("DemoApp.Models.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnhBia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapDo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("CoBan");

                    b.Property<int?>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaTien")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("MaKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTaNgan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("BanNhap");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("MaKhoaHoc")
                        .IsUnique();

                    b.HasIndex("TrangThai");

                    b.HasIndex("UserId");

                    b.ToTable("KhoaHoc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapDo = "CoBan",
                            DanhMucId = 1,
                            GiaTien = 0m,
                            MaKhoaHoc = "WEB001",
                            MoTaNgan = "Khóa học lập trình web cho người mới",
                            NgayTao = new DateTime(2025, 11, 19, 12, 59, 30, 339, DateTimeKind.Local).AddTicks(8367),
                            TenKhoaHoc = "HTML CSS JavaScript Cơ Bản",
                            TrangThai = "DaXuatBan",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CapDo = "CoBan",
                            DanhMucId = 2,
                            GiaTien = 299000m,
                            MaKhoaHoc = "MOB001",
                            MoTaNgan = "Học lập trình ứng dụng Android",
                            NgayTao = new DateTime(2025, 11, 19, 12, 59, 30, 339, DateTimeKind.Local).AddTicks(8370),
                            TenKhoaHoc = "Lập trình Android cơ bản",
                            TrangThai = "DaXuatBan",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("DemoApp.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("DemoApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Hà Nội",
                            Email = "admin@khoahoc.vn",
                            FullName = "Quản Trị Viên",
                            NumberPhone = "0123456789",
                            Password = "admin123",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "TP HCM",
                            Email = "user01@khoahoc.vn",
                            FullName = "Nguyễn Văn A",
                            NumberPhone = "0987654321",
                            Password = "user123",
                            RoleId = 2,
                            Username = "user01"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "Đà Nẵng",
                            Email = "user02@gmail.com",
                            FullName = "Lê Văn C",
                            NumberPhone = "0912345678",
                            Password = "user321",
                            RoleId = 2,
                            Username = "user02"
                        });
                });

            modelBuilder.Entity("DemoApp.Models.BaiHoc", b =>
                {
                    b.HasOne("DemoApp.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("BaiHoc")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("DemoApp.Models.Cart", b =>
                {
                    b.HasOne("DemoApp.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DemoApp.Models.DangKyKhoaHoc", b =>
                {
                    b.HasOne("DemoApp.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DangKyKhoaHoc")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoApp.Models.User", "user")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("user");
                });

            modelBuilder.Entity("DemoApp.Models.KhoaHoc", b =>
                {
                    b.HasOne("DemoApp.Models.DanhMuc", "DanhMuc")
                        .WithMany("KhoaHoc")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DemoApp.Models.User", "user")
                        .WithMany("KhoaHocDay")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("user");
                });

            modelBuilder.Entity("DemoApp.Models.User", b =>
                {
                    b.HasOne("DemoApp.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DemoApp.Models.DanhMuc", b =>
                {
                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("DemoApp.Models.KhoaHoc", b =>
                {
                    b.Navigation("BaiHoc");

                    b.Navigation("DangKyKhoaHoc");
                });

            modelBuilder.Entity("DemoApp.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DemoApp.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("DangKyKhoaHocs");

                    b.Navigation("KhoaHocDay");
                });
#pragma warning restore 612, 618
        }
    }
}
