// <auto-generated />
using System;
using DemoApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DemoApp.Models.BaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DuongDanNoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiNoiDung")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Video");

                    b.Property<string>("TenBaiHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("BaiHoc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DuongDanNoiDung = "https://www.youtube.com/watch?v=S3nx34WFXjI&list=PLZPZq0r_RZOMHoXIcxze_lP97j2Ase2on",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Lộ Trình Học Lập Trình Cho Người Mới",
                            ThoiLuong = 0,
                            ThuTuHienThi = 1
                        },
                        new
                        {
                            Id = 2,
                            DuongDanNoiDung = "https://www.youtube.com/watch?v=74B6PXO97Tw&list=PLux-_phi0Rz0Hq9fDP4TlOulBl8APKp79&index=2",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Làm Quen Với Ngôn Ngữ Lập Trình C++",
                            ThoiLuong = 0,
                            ThuTuHienThi = 2
                        },
                        new
                        {
                            Id = 3,
                            DuongDanNoiDung = "https://www.youtube.com/watch?v=y-_fNgvSfjc&list=PLux-_phi0Rz0Hq9fDP4TlOulBl8APKp79&index=3",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Toàn Tập Về Các Toán Tử Cơ Bản Trong C++ (Phần 1)",
                            ThoiLuong = 0,
                            ThuTuHienThi = 3
                        },
                        new
                        {
                            Id = 4,
                            DuongDanNoiDung = "https://www.youtube.com/watch?v=y-_fNgvSfjc&list=PLux-_phi0Rz0Hq9fDP4TlOulBl8APKp79&index=3",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Toàn Tập Về Các Toán Tử Cơ Bản Trong C++ (Phần 2)",
                            ThoiLuong = 0,
                            ThuTuHienThi = 4
                        },
                        new
                        {
                            Id = 5,
                            DuongDanNoiDung = "https://www.youtube.com/watch?v=R6plN3FvzFY&list=PL_-VfJajZj0U9nEXa4qyfB4U5ZIYCMPlz",
                            KhoaHocId = 2,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Tổng quan về khóa học HTML CSS",
                            ThoiLuong = 0,
                            ThuTuHienThi = 1
                        },
                        new
                        {
                            Id = 6,
                            DuongDanNoiDung = "http://youtube.com/watch?v=zwsPND378OQ&list=PL_-VfJajZj0U9nEXa4qyfB4U5ZIYCMPlz&index=2",
                            KhoaHocId = 2,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "HTML CSS là gì? | Ví dụ trực quan về HTML & CSS",
                            ThoiLuong = 0,
                            ThuTuHienThi = 2
                        },
                        new
                        {
                            Id = 7,
                            DuongDanNoiDung = "https://www.youtube.com/watch?v=7BJiPyN4zZ0&list=PL_-VfJajZj0U9nEXa4qyfB4U5ZIYCMPlz&index=3",
                            KhoaHocId = 2,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Làm quen với Dev tools",
                            ThoiLuong = 0,
                            ThuTuHienThi = 3
                        },
                        new
                        {
                            Id = 8,
                            DuongDanNoiDung = "https://www.youtube.com/watch?v=oPV2sjMG53U&list=PLZPZq0r_RZOMskz6MdsMOgxzheIyjo-BZ",
                            KhoaHocId = 3,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "SQL cho người mới bắt đầu",
                            ThoiLuong = 0,
                            ThuTuHienThi = 1
                        },
                        new
                        {
                            Id = 9,
                            DuongDanNoiDung = "https://www.youtube.com/watch?v=x0fSBAgBrOQ&list=PL_-VfJajZj0UXjlKfBwFX73usByw3Ph9Q",
                            KhoaHocId = 4,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "ReactJS là gì | Tại sao nên học ReactJS | Khóa học ReactJS miễn phí",
                            ThoiLuong = 0,
                            ThuTuHienThi = 1
                        });
                });

            modelBuilder.Entity("DemoApp.Models.BuoiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHoc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBuoiHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<int>("ThuTuBuoi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("BuoiHoc");
                });

            modelBuilder.Entity("DemoApp.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("DemoApp.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"), 1L, 1);

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("DemoApp.Models.DangKyKhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DangHoc");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "KhoaHocId")
                        .IsUnique();

                    b.ToTable("DangKyKhoaHoc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KhoaHocId = 1,
                            NgayDangKy = new DateTime(2025, 11, 28, 22, 53, 23, 848, DateTimeKind.Local).AddTicks(4552),
                            TrangThai = "DangHoc",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DemoApp.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("DanhMuc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "Học phát triển website",
                            TenDanhMuc = "Lập Trình Web",
                            ThuTuHienThi = 1,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "Phát triển ứng dụng di động",
                            TenDanhMuc = "Lập Trình Mobile",
                            ThuTuHienThi = 2,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            MoTa = "Cơ sở dữ liệu, SQL, backend",
                            TenDanhMuc = "Cơ Sở Dữ Liệu & Backend",
                            ThuTuHienThi = 3,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 4,
                            MoTa = "React, Vue, Angular...",
                            TenDanhMuc = "Frontend Framework",
                            ThuTuHienThi = 4,
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("DemoApp.Models.DiemDanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BuoiHocId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDiemDanh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("present");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuoiHocId");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("UserId");

                    b.ToTable("DiemDanh");
                });

            modelBuilder.Entity("DemoApp.Models.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnhBia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapDo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("CoBan");

                    b.Property<int?>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaTien")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("MaKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTaNgan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("BanNhap");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("MaKhoaHoc")
                        .IsUnique();

                    b.HasIndex("TrangThai");

                    b.HasIndex("UserId");

                    b.ToTable("KhoaHoc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnhBia = "cpp.jpg",
                            CapDo = "CoBan",
                            DanhMucId = 3,
                            GiaTien = 150000m,
                            MaKhoaHoc = "CPP001",
                            MoTaNgan = "Khóa học lập trình C++ cho người mới",
                            NgayTao = new DateTime(2025, 11, 28, 22, 53, 23, 848, DateTimeKind.Local).AddTicks(4455),
                            TenKhoaHoc = "Lập trình C++",
                            TrangThai = "DaXuatBan",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnhBia = "htmlcss.jpg",
                            CapDo = "CoBan",
                            DanhMucId = 1,
                            GiaTien = 300000m,
                            MaKhoaHoc = "HTMLCSS001",
                            MoTaNgan = "Khóa học HTML CSS cơ bản",
                            NgayTao = new DateTime(2025, 11, 28, 22, 53, 23, 848, DateTimeKind.Local).AddTicks(4459),
                            TenKhoaHoc = "Lập trình HTML và CSS",
                            TrangThai = "DaXuatBan",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AnhBia = "sql.jpg",
                            CapDo = "CoBan",
                            DanhMucId = 3,
                            GiaTien = 250000m,
                            MaKhoaHoc = "SQL001",
                            MoTaNgan = "SQL cho người mới bắt đầu",
                            NgayTao = new DateTime(2025, 11, 28, 22, 53, 23, 848, DateTimeKind.Local).AddTicks(4462),
                            TenKhoaHoc = "Lập trình SQL",
                            TrangThai = "DaXuatBan",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            AnhBia = "react.jpg",
                            CapDo = "CoBan",
                            DanhMucId = 4,
                            GiaTien = 500000m,
                            MaKhoaHoc = "REACT001",
                            MoTaNgan = "Khóa học ReactJS cơ bản",
                            NgayTao = new DateTime(2025, 11, 28, 22, 53, 23, 848, DateTimeKind.Local).AddTicks(4465),
                            TenKhoaHoc = "Lập trình React",
                            TrangThai = "DaXuatBan",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DemoApp.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("DemoApp.Models.TienDoHocTap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BaiHocId")
                        .HasColumnType("int");

                    b.Property<bool>("DaHoanThanh")
                        .HasColumnType("bit");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiGianHoc")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TyLeHoanThanh")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("UserId");

                    b.ToTable("TienDoHocTap");
                });

            modelBuilder.Entity("DemoApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Hà Nội",
                            Email = "admin@khoahoc.vn",
                            FullName = "Quản Trị Viên",
                            NumberPhone = "0123456789",
                            Password = "admin123",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "TP HCM",
                            Email = "user01@khoahoc.vn",
                            FullName = "Nguyễn Văn A",
                            NumberPhone = "0987654321",
                            Password = "user123",
                            RoleId = 2,
                            Username = "user01"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "Đà Nẵng",
                            Email = "user02@gmail.com",
                            FullName = "Lê Văn C",
                            NumberPhone = "0912345678",
                            Password = "user321",
                            RoleId = 2,
                            Username = "user02"
                        });
                });

            modelBuilder.Entity("DemoApp.Models.BaiHoc", b =>
                {
                    b.HasOne("DemoApp.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("BaiHoc")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("DemoApp.Models.BuoiHoc", b =>
                {
                    b.HasOne("DemoApp.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("BuoiHocs")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("DemoApp.Models.Cart", b =>
                {
                    b.HasOne("DemoApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DemoApp.Models.User", null)
                        .WithMany("Carts")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DemoApp.Models.CartItem", b =>
                {
                    b.HasOne("DemoApp.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DemoApp.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("DemoApp.Models.DangKyKhoaHoc", b =>
                {
                    b.HasOne("DemoApp.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DangKyKhoaHoc")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoApp.Models.User", "user")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("user");
                });

            modelBuilder.Entity("DemoApp.Models.DiemDanh", b =>
                {
                    b.HasOne("DemoApp.Models.BuoiHoc", "BuoiHoc")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("BuoiHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoApp.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoApp.Models.User", "User")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuoiHoc");

                    b.Navigation("KhoaHoc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DemoApp.Models.KhoaHoc", b =>
                {
                    b.HasOne("DemoApp.Models.DanhMuc", "DanhMuc")
                        .WithMany("KhoaHoc")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DemoApp.Models.User", "user")
                        .WithMany("KhoaHoc")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("user");
                });

            modelBuilder.Entity("DemoApp.Models.TienDoHocTap", b =>
                {
                    b.HasOne("DemoApp.Models.BaiHoc", "BaiHoc")
                        .WithMany("TienDoHocTap")
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoApp.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("TienDoHocTap")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoApp.Models.User", "User")
                        .WithMany("TienDoHocTap")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaiHoc");

                    b.Navigation("KhoaHoc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DemoApp.Models.User", b =>
                {
                    b.HasOne("DemoApp.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DemoApp.Models.BaiHoc", b =>
                {
                    b.Navigation("TienDoHocTap");
                });

            modelBuilder.Entity("DemoApp.Models.BuoiHoc", b =>
                {
                    b.Navigation("DiemDanhs");
                });

            modelBuilder.Entity("DemoApp.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DemoApp.Models.DanhMuc", b =>
                {
                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("DemoApp.Models.KhoaHoc", b =>
                {
                    b.Navigation("BaiHoc");

                    b.Navigation("BuoiHocs");

                    b.Navigation("DangKyKhoaHoc");

                    b.Navigation("DiemDanhs");

                    b.Navigation("TienDoHocTap");
                });

            modelBuilder.Entity("DemoApp.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DemoApp.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("DangKyKhoaHocs");

                    b.Navigation("DiemDanhs");

                    b.Navigation("KhoaHoc");

                    b.Navigation("TienDoHocTap");
                });
#pragma warning restore 612, 618
        }
    }
}
