// <auto-generated />
using System;
using DemoApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DemoApp.Models.BaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DuongDanNoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiNoiDung")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Video");

                    b.Property<string>("TenBaiHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("BaiHoc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DuongDanNoiDung = "bai-1-gioi-thieu-web.mp4",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Giới thiệu về Web Development",
                            ThuTuHienThi = 1
                        },
                        new
                        {
                            Id = 2,
                            DuongDanNoiDung = "bai-2-cau-truc-html.mp4",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Cấu trúc HTML cơ bản",
                            ThuTuHienThi = 2
                        },
                        new
                        {
                            Id = 3,
                            DuongDanNoiDung = "bai-3-the-html-thong-dung.mp4",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Các thẻ HTML thông dụng",
                            ThuTuHienThi = 3
                        },
                        new
                        {
                            Id = 4,
                            DuongDanNoiDung = "bai-4-form-input.mp4",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Form và Input trong HTML",
                            ThuTuHienThi = 4
                        },
                        new
                        {
                            Id = 5,
                            DuongDanNoiDung = "bai-5-css-box-model.mp4",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "CSS Selectors và Box Model",
                            ThuTuHienThi = 5
                        },
                        new
                        {
                            Id = 6,
                            DuongDanNoiDung = "bai-6-flexbox-grid.mp4",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Flexbox và Grid Layout",
                            ThuTuHienThi = 6
                        },
                        new
                        {
                            Id = 7,
                            DuongDanNoiDung = "bai-7-js-co-ban.mp4",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "JavaScript cơ bản - Variables & Functions",
                            ThuTuHienThi = 7
                        },
                        new
                        {
                            Id = 8,
                            DuongDanNoiDung = "bai-8-dom-manipulation.mp4",
                            KhoaHocId = 1,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "DOM Manipulation",
                            ThuTuHienThi = 8
                        },
                        new
                        {
                            Id = 9,
                            DuongDanNoiDung = "bai-9-du-an-portfolio.pdf",
                            KhoaHocId = 1,
                            LoaiNoiDung = "PDF",
                            TenBaiHoc = "Dự án Portfolio Website",
                            ThuTuHienThi = 9
                        },
                        new
                        {
                            Id = 10,
                            DuongDanNoiDung = "bai-10-gioi-thieu-android.mp4",
                            KhoaHocId = 2,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Giới thiệu Android Development",
                            ThuTuHienThi = 1
                        },
                        new
                        {
                            Id = 11,
                            DuongDanNoiDung = "bai-11-cai-dat-android-studio.mp4",
                            KhoaHocId = 2,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Cài đặt Android Studio",
                            ThuTuHienThi = 2
                        },
                        new
                        {
                            Id = 12,
                            DuongDanNoiDung = "bai-12-layout-xml.mp4",
                            KhoaHocId = 2,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Layout XML cơ bản",
                            ThuTuHienThi = 3
                        },
                        new
                        {
                            Id = 13,
                            DuongDanNoiDung = "bai-13-layout-comparison.mp4",
                            KhoaHocId = 2,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "LinearLayout vs RelativeLayout",
                            ThuTuHienThi = 4
                        },
                        new
                        {
                            Id = 14,
                            DuongDanNoiDung = "bai-14-xu-ly-su-kien.mp4",
                            KhoaHocId = 2,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Xử lý sự kiện Click",
                            ThuTuHienThi = 5
                        },
                        new
                        {
                            Id = 15,
                            DuongDanNoiDung = "bai-15-intent-navigation.mp4",
                            KhoaHocId = 2,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Intent và Navigation",
                            ThuTuHienThi = 6
                        },
                        new
                        {
                            Id = 16,
                            DuongDanNoiDung = "bai-16-recyclerview.mp4",
                            KhoaHocId = 2,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "RecyclerView cơ bản",
                            ThuTuHienThi = 7
                        },
                        new
                        {
                            Id = 17,
                            DuongDanNoiDung = "bai-17-du-an-todo-list.pdf",
                            KhoaHocId = 2,
                            LoaiNoiDung = "PDF",
                            TenBaiHoc = "Dự án ứng dụng Todo List",
                            ThuTuHienThi = 8
                        },
                        new
                        {
                            Id = 18,
                            DuongDanNoiDung = "bai-18-gioi-thieu-data-science.mp4",
                            KhoaHocId = 3,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Giới thiệu Data Science",
                            ThuTuHienThi = 1
                        },
                        new
                        {
                            Id = 19,
                            DuongDanNoiDung = "bai-19-cai-dat-moi-truong.mp4",
                            KhoaHocId = 3,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Cài đặt môi trường Python & Jupyter",
                            ThuTuHienThi = 2
                        },
                        new
                        {
                            Id = 20,
                            DuongDanNoiDung = "bai-20-pandas-dataframes.mp4",
                            KhoaHocId = 3,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Pandas cơ bản - DataFrames",
                            ThuTuHienThi = 3
                        },
                        new
                        {
                            Id = 21,
                            DuongDanNoiDung = "bai-21-data-cleaning.mp4",
                            KhoaHocId = 3,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Data Cleaning với Pandas",
                            ThuTuHienThi = 4
                        },
                        new
                        {
                            Id = 22,
                            DuongDanNoiDung = "bai-22-matplotlib.mp4",
                            KhoaHocId = 3,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Data Visualization với Matplotlib",
                            ThuTuHienThi = 5
                        },
                        new
                        {
                            Id = 23,
                            DuongDanNoiDung = "bai-23-seaborn.mp4",
                            KhoaHocId = 3,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Seaborn cho visualization nâng cao",
                            ThuTuHienThi = 6
                        },
                        new
                        {
                            Id = 24,
                            DuongDanNoiDung = "bai-24-phan-tich-du-lieu.pdf",
                            KhoaHocId = 3,
                            LoaiNoiDung = "PDF",
                            TenBaiHoc = "Phân tích dữ liệu thực tế",
                            ThuTuHienThi = 7
                        },
                        new
                        {
                            Id = 25,
                            DuongDanNoiDung = "bai-25-gioi-thieu-ui-ux.mp4",
                            KhoaHocId = 4,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Giới thiệu UI/UX Design",
                            ThuTuHienThi = 1
                        },
                        new
                        {
                            Id = 26,
                            DuongDanNoiDung = "bai-26-nguyen-ly-thiet-ke.mp4",
                            KhoaHocId = 4,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Nguyên lý thiết kế cơ bản",
                            ThuTuHienThi = 2
                        },
                        new
                        {
                            Id = 27,
                            DuongDanNoiDung = "bai-27-color-theory.mp4",
                            KhoaHocId = 4,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Color Theory trong UI Design",
                            ThuTuHienThi = 3
                        },
                        new
                        {
                            Id = 28,
                            DuongDanNoiDung = "bai-28-typography.mp4",
                            KhoaHocId = 4,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Typography cơ bản",
                            ThuTuHienThi = 4
                        },
                        new
                        {
                            Id = 29,
                            DuongDanNoiDung = "bai-29-wireframing-figma.mp4",
                            KhoaHocId = 4,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Wireframing với Figma",
                            ThuTuHienThi = 5
                        },
                        new
                        {
                            Id = 30,
                            DuongDanNoiDung = "bai-30-prototyping.mp4",
                            KhoaHocId = 4,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Prototyping và Interaction",
                            ThuTuHienThi = 6
                        },
                        new
                        {
                            Id = 31,
                            DuongDanNoiDung = "bai-31-du-an-mobile-app.pdf",
                            KhoaHocId = 4,
                            LoaiNoiDung = "PDF",
                            TenBaiHoc = "Dự án thiết kế Mobile App",
                            ThuTuHienThi = 7
                        },
                        new
                        {
                            Id = 32,
                            DuongDanNoiDung = "bai-32-design-system.mp4",
                            KhoaHocId = 4,
                            LoaiNoiDung = "Video",
                            TenBaiHoc = "Design System cơ bản",
                            ThuTuHienThi = 8
                        });
                });

            modelBuilder.Entity("DemoApp.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("DemoApp.Models.DangKyKhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DangHoc");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "KhoaHocId")
                        .IsUnique();

                    b.ToTable("DangKyKhoaHoc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KhoaHocId = 1,
                            NgayDangKy = new DateTime(2025, 11, 24, 22, 42, 10, 173, DateTimeKind.Local).AddTicks(9760),
                            TrangThai = "DangHoc",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            KhoaHocId = 2,
                            NgayDangKy = new DateTime(2025, 11, 24, 22, 42, 10, 173, DateTimeKind.Local).AddTicks(9800),
                            TrangThai = "DangHoc",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DemoApp.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("DanhMuc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "Học phát triển website",
                            TenDanhMuc = "Lập Trình Web",
                            ThuTuHienThi = 1,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "Phát triển ứng dụng di động",
                            TenDanhMuc = "Lập Trình Mobile",
                            ThuTuHienThi = 2,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            MoTa = "Làm việc với Python",
                            TenDanhMuc = "Data Science",
                            ThuTuHienThi = 3,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 4,
                            MoTa = "UI (Giao diện người dùng), UX (Trải nghiệm người dùng)",
                            TenDanhMuc = "Thiết kế UX/UI Cơ Bản",
                            ThuTuHienThi = 4,
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("DemoApp.Models.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnhBia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapDo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("CoBan");

                    b.Property<int?>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaTien")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("MaKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTaChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaNgan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("BanNhap");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("MaKhoaHoc")
                        .IsUnique();

                    b.HasIndex("TrangThai");

                    b.HasIndex("UserId");

                    b.ToTable("KhoaHoc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnhBia = "anh1.jpg",
                            CapDo = "CoBan",
                            DanhMucId = 1,
                            GiaTien = 399000m,
                            MaKhoaHoc = "WEB001",
                            MoTaChiTiet = "Biến bạn từ người mới bắt đầu thành người xây dựng website chuyên nghiệp!Khóa học HTML CSS JavaScript Cơ Bản chính là nền tảng vững chắc đầu tiên dành cho bạn!Khóa học được thiết kế từ CƠ BẢN đến NÂNG CAO, phù hợp cho người mới bắt đầu. Bạn chỉ cần: Chăm chỉ và kiên trì thực hành,không ngại hỏi đáp, tích cực tương tác,chủ động đưa ra thắc mắc trong quá trình học tậpSau khóa học, bạn ĐỦ NĂNG LỰC để: Ứng tuyển vị trí Fresher Frontend Developer, tự tin xây dựng website responsive, phát triển các dự án cá nhân chất lượngĐĂNG KÝ NGAY ĐỂ BIẾN ĐAM MÊ THÀNH NGHỀ NGHIỆP!",
                            MoTaNgan = "Khóa học lập trình web cho người mới",
                            NgayTao = new DateTime(2025, 11, 24, 22, 42, 10, 173, DateTimeKind.Local).AddTicks(9703),
                            TenKhoaHoc = "HTML CSS JavaScript Cơ Bản",
                            TrangThai = "DaXuatBan",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnhBia = "anh3.jpg",
                            CapDo = "CoBan",
                            DanhMucId = 2,
                            GiaTien = 299000m,
                            MaKhoaHoc = "MOB001",
                            MoTaChiTiet = "Biến ý tưởng thành ứng dụng thực tế - Khởi đầu sự nghiệp Mobile Developer!Khóa học Lập trình Android Cơ Bản chính là chìa khóa mở cánh cửa vào thế giới phát triển di động!Khóa học được thiết kế từ CƠ BẢN đến THỰC HÀNH, chỉ cần bạn: Chăm chỉ thực hành và không ngại thử nghiệm, tích cực hỏi đáp và chia sẻ khó khăn, có laptop cấu hình tối thiểu để cài đặt Android StudioSau khóa học, bạn HOÀN TOÀN ĐỦ NĂNG LỰC để: Ứng tuyển vị trí Fresher Android Developer, tự phát triển ứng dụng Android hoàn chỉnh, hiểu và áp dụng Android architecture patterns, kết nối với RESTful API và xử lý data public ứng dụng lên Google Play StoreĐĂNG KÝ NGAY ĐỂ BIẾN ĐAM MÊ THÀNH NGHỀ NGHIỆP!",
                            MoTaNgan = "Học lập trình ứng dụng Android",
                            NgayTao = new DateTime(2025, 11, 24, 22, 42, 10, 173, DateTimeKind.Local).AddTicks(9705),
                            TenKhoaHoc = "Lập trình Android cơ bản",
                            TrangThai = "DaXuatBan",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            AnhBia = "anh2.jpg",
                            CapDo = "TrungCap",
                            DanhMucId = 3,
                            GiaTien = 450000m,
                            MaKhoaHoc = "DATA001",
                            MoTaChiTiet = "Biến dữ liệu thô thành insights giá trị - Khởi đầu sự nghiệp Data Scientist!Khóa học Python Data Science sẽ trang bị cho bạn công cụ để trở thành chuyên gia phân tích dữ liệu thời đại 4.0!Khóa học được thiết kế từ CƠ BẢN đến CHUYÊN SÂU, chỉ cần bạn: Tư duy logic và ham học hỏi, chăm chỉ thực hành case study thực tế, không ngại hỏi đáp về các vấn đề dataSau khóa học, bạn HOÀN TOÀN có thể: Ứng tuyển thành công vị trí Fresher Data Analyst, tự tin phỏng vấn với technical knowledge, xử lý real-world data problems, tiếp tục học lên Advanced Data ScienceĐĂNG KÝ NGAY ĐỂ BIẾN ĐAM MÊ THÀNH NGHỀ NGHIỆP!",
                            MoTaNgan = "Khoa học dữ liệu với Python cơ bản",
                            NgayTao = new DateTime(2025, 11, 19, 22, 42, 10, 173, DateTimeKind.Local).AddTicks(9707),
                            TenKhoaHoc = "Python Data Science",
                            TrangThai = "DaXuatBan",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            AnhBia = "anh4.jpg",
                            CapDo = "CoBan",
                            DanhMucId = 4,
                            GiaTien = 350000m,
                            MaKhoaHoc = "UIUX001",
                            MoTaChiTiet = "Biến ý tưởng thành trải nghiệm người dùng tuyệt vời - Khởi đầu sự nghiệp Designer chuyên nghiệp!Khóa học Thiết kế UI/UX Cơ Bản sẽ biến bạn từ người mới bắt đầu thành designer có tư duy hệ thống!Khóa học được thiết kế từ NGUYÊN LÝ đến THỰC HÀNH, chỉ cần bạn: Đam mê sáng tạo và yêu thích cái đẹp, tư duy logic và hướng về người dùng, chăm chỉ thực hành và không ngại feedbackSau khóa học, bạn HOÀN TOÀN có thể: Ứng tuyển thành công vị trí Fresher UI/UX Designer, làm freelance project với mức lương 2-5 triệu/project, tiếp tục học nâng cao lên Senior level, tự quản lý design process từ A-ZĐĂNG KÝ NGAY ĐỂ BIẾN ĐAM MÊ THÀNH NGHỀ NGHIỆP!",
                            MoTaNgan = "Học thiết kế giao diện người dùng chuyên nghiệp",
                            NgayTao = new DateTime(2025, 11, 22, 22, 42, 10, 173, DateTimeKind.Local).AddTicks(9714),
                            TenKhoaHoc = "Thiết kế UI/UX cơ bản",
                            TrangThai = "BanNhap",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("DemoApp.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("DemoApp.Models.TienDoHocTap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BaiHocId")
                        .HasColumnType("int");

                    b.Property<bool>("DaHoanThanh")
                        .HasColumnType("bit");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiGianHoc")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TyLeHoanThanh")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("UserId");

                    b.ToTable("TienDoHocTap");
                });

            modelBuilder.Entity("DemoApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Hà Nội",
                            Email = "admin@khoahoc.vn",
                            FullName = "Quản Trị Viên",
                            NumberPhone = "0123456789",
                            Password = "admin123",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "TP HCM",
                            Email = "user01@khoahoc.vn",
                            FullName = "Nguyễn Văn A",
                            NumberPhone = "0987654321",
                            Password = "user123",
                            RoleId = 2,
                            Username = "user01"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "Đà Nẵng",
                            Email = "user02@gmail.com",
                            FullName = "Lê Văn C",
                            NumberPhone = "0912345678",
                            Password = "user321",
                            RoleId = 2,
                            Username = "user02"
                        });
                });

            modelBuilder.Entity("DemoApp.Models.BaiHoc", b =>
                {
                    b.HasOne("DemoApp.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("BaiHoc")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("DemoApp.Models.Cart", b =>
                {
                    b.HasOne("DemoApp.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DemoApp.Models.DangKyKhoaHoc", b =>
                {
                    b.HasOne("DemoApp.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DangKyKhoaHoc")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoApp.Models.User", "user")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("user");
                });

            modelBuilder.Entity("DemoApp.Models.KhoaHoc", b =>
                {
                    b.HasOne("DemoApp.Models.DanhMuc", "DanhMuc")
                        .WithMany("KhoaHoc")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DemoApp.Models.User", "user")
                        .WithMany("KhoaHoc")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("user");
                });

            modelBuilder.Entity("DemoApp.Models.TienDoHocTap", b =>
                {
                    b.HasOne("DemoApp.Models.BaiHoc", "BaiHoc")
                        .WithMany("TienDoHocTap")
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoApp.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("TienDoHocTap")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoApp.Models.User", "User")
                        .WithMany("TienDoHocTap")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaiHoc");

                    b.Navigation("KhoaHoc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DemoApp.Models.User", b =>
                {
                    b.HasOne("DemoApp.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DemoApp.Models.BaiHoc", b =>
                {
                    b.Navigation("TienDoHocTap");
                });

            modelBuilder.Entity("DemoApp.Models.DanhMuc", b =>
                {
                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("DemoApp.Models.KhoaHoc", b =>
                {
                    b.Navigation("BaiHoc");

                    b.Navigation("DangKyKhoaHoc");

                    b.Navigation("TienDoHocTap");
                });

            modelBuilder.Entity("DemoApp.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DemoApp.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("DangKyKhoaHocs");

                    b.Navigation("KhoaHoc");

                    b.Navigation("TienDoHocTap");
                });
#pragma warning restore 612, 618
        }
    }
}
